version: "3"

services:
  spark:
    image: prod
    container_name: p8tensorspark
    ports:
      - "10888:8888"
      - "4040:4040"
    volumes:
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=wiwi_super_secret_code_project_token

#   namenode:
#      image: apache/hadoop:3
#      hostname: namenode
#      command: ["hdfs", "namenode"]
#      ports:
#        - 9870:9870
#      env_file:
#        - ./config
#      environment:
#          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
#   datanode:
#      image: apache/hadoop:3
#      command: ["hdfs", "datanode"]
#      env_file:
#        - ./config      
#   resourcemanager:
#      image: apache/hadoop:3
#      hostname: resourcemanager
#      command: ["yarn", "resourcemanager"]
#      ports:
#         - 8088:8088
#      env_file:
#        - ./config
#      volumes:
#        - ./test.sh:/opt/test.sh
#   nodemanager:
#      image: apache/hadoop:3
#      command: ["yarn", "nodemanager"]
#      env_file:
#        - ./config