folders=(
    "Apple Braeburn"
    "Apple Crimson Snow"
    "Apple Golden 1"
    "Apple Golden 2"
    "Apple Golden 3"
    "Apple Granny Smith"
    "Apple Pink Lady"
    "Apple Red 1"
    "Apple Red 2"
    "Apple Red 3"
    "Apple Red Delicious"
    "Apple Red Yellow 1"
    "Apple Red Yellow 2"
    "Apricot"
    "Avocado"
    "Avocado ripe"
    "Banana"
    "Banana Lady Finger"
    "Banana Red"
    "Beetroot"
    "Blueberry"
    "Cactus fruit"
    "Cantaloupe 1"
    "Cantaloupe 2"
    "Carambula"
    "Cauliflower"
    "Cherry 1"
    "Cherry 2"
    "Cherry Rainier"
    "Cherry Wax Black"
)

for folder in "${folders[@]}"
do
  echo "Populate $folder"
  mkdir "data/Test1/$folder"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/0_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/30_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/60_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/90_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/120_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/150_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/170_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/180_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/190_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/200_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/210_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/240_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/270_100.jpg" "data/Test1/$folder/"
  cp "fruits/fruits-360_dataset/fruits-360/Training/$folder/300_100.jpg" "data/Test1/$folder/"
done